# Generated by Django 3.2.7 on 2022-09-16 07:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+917000000000', max_length=30, region=None, verbose_name='Phone number'),
        ),
    ]
