# Generated by Django 3.2.7 on 2022-09-16 07:42

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='Chandigarh', max_length=180, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='property',
            name='postal_code',
            field=models.CharField(default='140308', max_length=100, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_number',
            field=models.IntegerField(default=798, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Property Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_address',
            field=models.CharField(default='Sector 77', max_length=150, verbose_name='Street Address'),
        ),
    ]
