# Generated by Django 3.2.7 on 2022-09-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20220916_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Price'),
        ),
    ]
